### PR TITLE
fix: interpret empty maps as always valid

### PR DESCRIPTION
**Pull request by polvalente**
This PR aims to solve #57 

As the evidence below shows, empty maps should also be treated as success in case of a `%{required(...) => ...}` spec as well as `%{x => ...}`. Dialyzer also give a success in theses cases.

Module of case-study:
```elixir
defmodule T do
  @spec f() :: %{required(atom()) => any()}
  def f, do: %{}

  @spec g() :: %{atom() => any()}
  def g, do: %{}
end
```

Defined spec for the module above. Notice that in both cases the type was parsed as `:map_field_exact`
```elixir
iex(1)> Code.Typespec.fetch_specs(T)
{:ok,
 [
   {{:g, 0},
    [
      {:type, 5, :fun,
       [
         {:type, 5, :product, []},
         {:type, 5, :map,
          [
            {:type, 5, :map_field_exact,
             [{:type, 5, :atom, []}, {:type, 5, :any, []}]}
          ]}
       ]}
    ]},
   {{:f, 0},
    [
      {:type, 2, :fun,
       [
         {:type, 2, :product, []},
         {:type, 2, :map,
          [
            {:type, 2, :map_field_exact,
             [{:type, 2, :atom, []}, {:type, 2, :any, []}]}
          ]}
       ]}
    ]}
 ]}
```

Dialyzer is also happy with the implementations
```shell
mix dialyzer
Finding suitable PLTs
Checking PLT...
[:compiler, :crypto, :dialyxir, :dialyzer, :elixir, :erlex, :hipe, :kernel, :logger, :mix, :stdlib, :wx]
PLT is up to date!
No :ignore_warnings opt specified in mix.exs and default does not exist.

Starting Dialyzer
[
  check_plt: false,
  init_plt: '<<REDACTED>>/_build/dev/dialyxir_erlang-22.3.4.2_elixir-1.11.0_deps-dev.plt',
  files: ['<<REDACTED>>/_build/dev/lib/teste/ebin/Elixir.T.beam'],
  warnings: [:unknown]
]
Total errors: 0, Skipped: 0, Unnecessary Skips: 0
done in 0m1.87s
done (passed successfully)
```

Please let me know if any changes are required!

### CODE REVIEW

**Comment by polvalente** [comment]
By the way, I also added `:ecto` as an optional dependency so the problematic `Ecto.Changeset` struct was available for specific testing. However, if you feel like this is not needed, I can refactor and implement a similar spec to `Ecto.Changeset.t`

**Comment by polvalente** [comment]
Actually, after reading #57 more thoroughly, I'm not entirely sure that the problems described there are the same as the ones I've encountered. The PR is valid otherwise

**Comment by msz** [comment]
Thanks you for this!

I think if you are aiming to have a possibly empty map, you can use `%{optional(...) => ...}`. This way, in other cases you still have the option to assert that there needs to be at least one key-value pair of a given type via using `%{required(...) => ...}`. So I would keep the current behaviour.

We are aiming to be compatible with Dialyzer. If Dialyzer fails something, we should fail it too. But we can still be stricter in cases where Dialyzer succeeds and the better outcome would be to fail. I think this is one of these cases.

Thanks for your work anyway, really appreciated!

**Comment by polvalente** [comment]
@msz I see! Upon further reading, it seems that it's either the Ecto.Changeset.t spec that's incompatible wit the actual behavior, or the doc that isn't clear if empty maps are considered valid for these cases. 

https://hexdocs.pm/elixir/typespecs.html

This says that both notations are required key-value pairs, and Ecto.Changeset does use the notation without the "required" call.

**Comment by polvalente** [comment]
@msz https://github.com/elixir-ecto/ecto/commit/1a4b4f6c7979b7469275e0db4deefc59e2b68275

This solves the issue. I'll close this PR for now!

**Comment by msz** [comment]
Nice, thank you!

**Pull request closed without merging**
