### PR TITLE
Migrate Agent cache -> Persistent Term for ~5x performance improvement

### PR DESCRIPTION
**Pull request by SophisticaSean**
I did some benchmarking and found the Agent process was a significant bottleneck to the Hammox flow, so I moved the typespec caches over to ETS and it has lead to a 2.5x performance improvement.

Hammox 0.5.0 (current performance):
```
Operating System: Linux
CPU Information: AMD Ryzen 9 5950X 16-Core Processor
Number of Available Cores: 32
Available memory: 100.53 GB
Elixir 1.13.2
Erlang 24.2

Benchmark suite executing with the following configuration:
warmup: 10 s
time: 30 s
memory time: 5 s
parallel: 1
inputs: none specified
Estimated total run time: 1.50 min

Benchmarking hammox_run_kyc_check...
Benchmarking mox_run_kyc_check...

Name                           ips        average  deviation         median         99t
h %
mox_run_kyc_check           4.48 K        0.22 ms   ±561.54%       0.150 ms        0.33
 ms
hammox_run_kyc_check      0.0145 K       68.82 ms     ±2.54%       68.40 ms       77.14
 ms

Comparison:
mox_run_kyc_check           4.48 K
hammox_run_kyc_check      0.0145 K - 308.39x slower +68.60 ms

Memory usage statistics:

Name                         average  deviation         median         99th %
mox_run_kyc_check           0.131 MB     ±0.06%       0.131 MB       0.131 MB
hammox_run_kyc_check        36.28 MB     ±0.02%       36.28 MB       36.33 MB

Comparison:
mox_run_kyc_check           0.131 MB
hammox_run_kyc_check        36.28 MB - 276.90x memory usage +36.15 MB
```

This branch: 
```
Operating System: Linux
CPU Information: AMD Ryzen 9 5950X 16-Core Processor
Number of Available Cores: 32
Available memory: 100.53 GB
Elixir 1.13.2
Erlang 24.2

Benchmark suite executing with the following configuration:
warmup: 10 s
time: 30 s
memory time: 5 s
parallel: 1
inputs: none specified
Estimated total run time: 1.50 min

Benchmarking hammox_run_kyc_check...
Benchmarking mox_run_kyc_check...

Name                           ips        average  deviation         median         99t
h %
mox_run_kyc_check           4.44 K        0.23 ms   ±603.18%       0.150 ms        0.34
 ms
hammox_run_kyc_check      0.0366 K       27.29 ms    ±20.18%       25.88 ms       46.73
 ms

Comparison:
mox_run_kyc_check           4.44 K
hammox_run_kyc_check      0.0366 K - 121.09x slower +27.06 ms

Memory usage statistics:

Name                         average  deviation         median         99th %
mox_run_kyc_check           0.132 MB     ±0.07%       0.132 MB       0.132 MB
hammox_run_kyc_check        31.94 MB     ±0.13%       31.94 MB       32.01 MB

Comparison:
mox_run_kyc_check           0.132 MB
hammox_run_kyc_check        31.94 MB - 241.62x memory usage +31.80 MB
```

Important numbers:
0.5.0 Hammox: `0.0145 K IPS`
This branch: ` 0.0366 K`

This represents a 2.52x performance increase. This has had a measurable impact on our large Hammox heavy test suite and has reduced our overall test time by about 15-20%.

### CODE REVIEW

**Comment by SophisticaSean** [comment]
Still need telemetry documentation

**Comment by SophisticaSean** [comment]
docs written for telemetry on Hammox

**Review by msz — COMMENTED** [review]
This is awesome! It was on my list to do this and it's great to see that there is speedup. And I love the docs!

Two questions:
- Can we now drop the GenServer and run the Cache code in the same process to avoid overhead of copying data between processes?
- Could we have a separate module that wraps Hammox with telemetry instead of building it in directly? It's a bit counterintuitive to me to build telemetry into a (performance sensitive) testing tool by default. If we had Hammox and HammoxWithTelemetry then people could use the other one if they ever want to run a benchmark.

**Comment by SophisticaSean** [comment]
Awesome, planning on getting to this soon. Just changed jobs so life has been a smidge hectic.

**Comment by msz** [comment]
Hey there, are you planning to continue working on this? There are some sweet performance improvements here and I'd be happy to build on your work myself if you don't get the time to.

**Comment by Adzz** [comment]
I wonder if it might be worth benchmarking [persistent_term](https://www.erlang.org/doc/man/persistent_term.html) instead of ETS ? I would expect it to be faster than ETS.

**Comment by SophisticaSean** [comment]
Yeah I'll pick this back up. I changed jobs recently so have been a smidge busy but I'll spin this up and play with persistent_term as well! Thank you for the nudge and the suggestion!

**Comment by SophisticaSean** [comment]
alrighty, I need to play around with persistent term but this is ready to go outside of refactoring in persistent_term, I think we should do that in a separate PR anyway. @msz

**Comment by SophisticaSean** [comment]
Benchmarks with telemetry enabled:

```
╰─ MIX_ENV=test mix run benchmarks/hammox.exs
Compiling 678 files (.ex)
Generated genesis app
Operating System: Linux
CPU Information: AMD Ryzen 9 5950X 16-Core Processor
Number of Available Cores: 32
Available memory: 100.53 GB
Elixir 1.13.4
Erlang 24.3.3

Benchmark suite executing with the following configuration:
warmup: 10 s
time: 30 s
memory time: 5 s
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 1.50 min

Benchmarking hammox_run_kyc_check ...
Benchmarking mox_run_kyc_check ...

Name                           ips        average  deviation         median         99th %
mox_run_kyc_check           1.47 K        0.68 ms   ±551.35%        0.33 ms        0.73 ms
hammox_run_kyc_check      0.0425 K       23.52 ms    ±15.67%       22.70 ms       37.70 ms

Comparison:
mox_run_kyc_check           1.47 K
hammox_run_kyc_check      0.0425 K - 34.67x slower +22.84 ms

Memory usage statistics:

Name                         average  deviation         median         99th %
mox_run_kyc_check            0.28 MB     ±0.04%        0.28 MB        0.28 MB
hammox_run_kyc_check        32.15 MB     ±0.01%       32.15 MB       32.16 MB

Comparison:
mox_run_kyc_check            0.28 MB
hammox_run_kyc_check        32.15 MB - 114.15x memory usage +31.87 MB
```

Benchmarks with telemetry disabled:
```
╰─ MIX_ENV=test mix run benchmarks/hammox.exs
Compiling 201 files (.ex)
Generated genesis app
Operating System: Linux
CPU Information: AMD Ryzen 9 5950X 16-Core Processor
Number of Available Cores: 32
Available memory: 100.53 GB
Elixir 1.13.4
Erlang 24.3.3

Benchmark suite executing with the following configuration:
warmup: 10 s
time: 30 s
memory time: 5 s
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 1.50 min

Benchmarking hammox_run_kyc_check ...
Benchmarking mox_run_kyc_check ...

Name                           ips        average  deviation         median         99th %
mox_run_kyc_check           1.44 K        0.70 ms   ±558.35%        0.33 ms       16.52 ms
hammox_run_kyc_check      0.0524 K       19.09 ms     ±9.03%       18.74 ms       25.86 ms

Comparison:
mox_run_kyc_check           1.44 K
hammox_run_kyc_check      0.0524 K - 27.40x slower +18.39 ms

Memory usage statistics:

Name                         average  deviation         median         99th %
mox_run_kyc_check            0.28 MB     ±0.26%        0.28 MB        0.28 MB
hammox_run_kyc_check        31.41 MB     ±0.04%       31.42 MB       31.42 MB

Comparison:
mox_run_kyc_check            0.28 MB
hammox_run_kyc_check        31.41 MB - 112.36x memory usage +31.13 MB
```

About ~4ms extra on average when telemetry is enabled. Not too bad!

**Comment by SophisticaSean** [comment]
I removed the whole genserver and application.ex and here's the performance difference:

persistent_term, with telemetry enabled, without the Hammox.Cache GenServer:
```
╰─ MIX_ENV=test mix run benchmarks/hammox.exs
==> hammox
Compiling 1 file (.ex)
Generated hammox app
==> genesis
Compiling 201 files (.ex)
Compiling 2 files (.ex)
Generated genesis app
Operating System: Linux
CPU Information: AMD Ryzen 9 5950X 16-Core Processor
Number of Available Cores: 32
Available memory: 100.53 GB
Elixir 1.13.4
Erlang 24.3.3

Benchmark suite executing with the following configuration:
warmup: 10 s
time: 30 s
memory time: 5 s
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 1.50 min

Benchmarking hammox_run_kyc_check ...
Benchmarking mox_run_kyc_check ...

Name                           ips        average  deviation         median         99th %
mox_run_kyc_check           1.43 K        0.70 ms   ±567.13%        0.33 ms       17.24 ms
hammox_run_kyc_check      0.0629 K       15.90 ms    ±14.73%       15.13 ms       24.23 ms

Comparison:
mox_run_kyc_check           1.43 K
hammox_run_kyc_check      0.0629 K - 22.73x slower +15.20 ms

Memory usage statistics:

Name                         average  deviation         median         99th %
mox_run_kyc_check            0.28 MB     ±0.25%        0.28 MB        0.28 MB
hammox_run_kyc_check        15.81 MB     ±0.02%       15.82 MB       15.82 MB

Comparison:
mox_run_kyc_check            0.28 MB
hammox_run_kyc_check        15.81 MB - 56.57x memory usage +15.53 MB
```
persistent_term, with telemetry disabled, without the Hammox.Cache GenServer:
```
╰─ MIX_ENV=test mix run benchmarks/hammox.exs
Compiling 201 files (.ex)
Compiling 2 files (.ex)
Generated genesis app
Operating System: Linux
CPU Information: AMD Ryzen 9 5950X 16-Core Processor
Number of Available Cores: 32
Available memory: 100.53 GB
Elixir 1.13.4
Erlang 24.3.3

Benchmark suite executing with the following configuration:
warmup: 10 s
time: 30 s
memory time: 5 s
reduction time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 1.50 min

Benchmarking hammox_run_kyc_check ...
Benchmarking mox_run_kyc_check ...

Name                           ips        average  deviation         median         99th %
mox_run_kyc_check           1.47 K        0.68 ms   ±540.00%        0.33 ms        1.09 ms
hammox_run_kyc_check      0.0748 K       13.38 ms     ±9.18%       13.30 ms       17.64 ms

Comparison:
mox_run_kyc_check           1.47 K
hammox_run_kyc_check      0.0748 K - 19.62x slower +12.69 ms

Memory usage statistics:

Name                         average  deviation         median         99th %
mox_run_kyc_check            0.28 MB     ±0.14%        0.28 MB        0.28 MB
hammox_run_kyc_check        15.13 MB     ±0.00%       15.13 MB       15.14 MB

Comparison:
mox_run_kyc_check            0.28 MB
hammox_run_kyc_check        15.13 MB - 53.86x memory usage +14.85 MB
```
looks right around the same speed without the need for `lib/hammox/application.ex` and the GenServer over at `lib/hammox/cache.ex`

**Review by msz — COMMENTED** [review]
It's looking great! I gave it an initial look and I saw that a big chunk of this PR is actually also adding telemetry, along with all the docs and tests (thank you!). Would you be able to split these into two PRs, one for adding telemetry and one for replacing the Cache mechanism? It would make it easier to review and easier for bookkeeping overall 🙏

**Comment by SophisticaSean** [comment]
@msz Happy to do that. Please hold. :)

**Comment by SophisticaSean** [comment]
Alrighty, ready for a review!

**Review by msz — APPROVED** [review]
Short and sweet!

**Pull request merged**
